[package]
name = "noct-config"
version = "0.1.0"
license.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true, default-features = true }
dotenvy = { workspace = true }
figment = { workspace = true, features = ["toml", "env"] }
serde = { workspace = true, features = ["std", "derive"] }
tracing = { workspace = true }

[dev-dependencies]
figment = { workspace = true, features = ["test"] }
