[package]
name = "noct-web"
version = "0.1.0"
license.workspace = true
edition.workspace = true
publish = false

[features]
web-test = ["dep:noct-macros", "dep:hyper", "dep:tower"]

[dependencies]
noct-config = { path = "../config" }

anyhow = { workspace = true }
axum = { workspace = true, default-features = true, features = ["macros"] }
serde = { workspace = true, features = ["std", "derive"] }
serde_json = { workspace = true, features = ["std"] }
tokio = { workspace = true, default-features = true, features = ["full"] }
tower-http = { workspace = true, default-features = true, features = ["full"] }
tracing = { workspace = true }

noct-macros = { path = "../macros", optional = true }
hyper = { workspace = true, features = ["full"], optional = true }
tower = { workspace = true, features = ["full"], optional = true }

[dev-dependencies]
noct-web = { path = ".", features = ["web-test"] }
